# Generated by Django 3.1.12 on 2024-11-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='jogador@email.com', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='app.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('hora_evento', models.TimeField(blank=True, null=True)),
                ('jogadores', models.ManyToManyField(blank=True, to='app.Jogador')),
                ('personagem', models.ManyToManyField(blank=True, to='app.Personagem')),
            ],
        ),
    ]
